In [1]:
import pandas as pd
import numpy as np

In [2]:
def data(file):
    data = open(file,'r')
    f = []
    for x in data:
        l = x.split()
        f.append(l)
    f[0] = ["    "] + f[0]
    return f

In [3]:
#creating and loading matrix
n_dt=[]
n_dd=[]
n_tt=[]
n_dt=data("Data\gprc_dt.txt")
n_dd=data("Data\gprc_dd.txt")
n_tt=data("Data\gprc_tt.txt")

In [4]:
print(len(n_dt))
print(len(n_dt[0]))
print(len(n_dd))
print(len(n_tt))

96
224
224
96


In [5]:
n_dt[1]

['hsa10161',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0

In [6]:
#removing headings text from data
x=len(n_dd)
y=len(n_dd[0])
n_dd_sum=[]
n_dd_2=np.empty([x-1,y-1], dtype=np.float)
for i in range(1,x):
    s=0.0
    for j in range(1,y):
        if(i!=0 and j!=0):
            n_dd_2[i-1][j-1]=n_dd[i][j]
            s+=float(n_dd[i][j])
    n_dd_sum.append(s)
print(n_dd_2)

[[1.       0.352941 0.096774 ... 0.16129  0.148148 0.107143]
 [0.352941 1.       0.181818 ... 0.138889 0.2      0.2     ]
 [0.096774 0.181818 1.       ... 0.130435 0.146341 0.093023]
 ...
 [0.16129  0.138889 0.130435 ... 1.       0.289474 0.324324]
 [0.148148 0.2      0.146341 ... 0.289474 1.       0.222222]
 [0.107143 0.2      0.093023 ... 0.324324 0.222222 1.      ]]


In [7]:
n_dd_2[0]

array([1.      , 0.352941, 0.096774, 0.107143, 0.222222, 0.096774,
       0.192308, 0.2     , 0.129032, 0.190476, 0.096774, 0.192308,
       0.083333, 0.      , 0.102564, 0.166667, 0.352941, 0.114286,
       0.153846, 0.108108, 0.210526, 0.142857, 0.130435, 0.217391,
       0.076923, 0.103448, 0.074074, 0.166667, 0.105263, 0.142857,
       0.16129 , 0.157895, 0.173913, 0.148148, 0.2     , 0.205882,
       0.3     , 0.086957, 0.153846, 0.      , 0.111111, 0.114286,
       0.148148, 0.133333, 0.071429, 0.066667, 0.      , 0.16    ,
       0.148148, 0.166667, 0.153846, 0.208333, 0.133333, 0.16    ,
       0.153846, 0.      , 0.125   , 0.166667, 0.173913, 0.2     ,
       0.135135, 0.128205, 0.2     , 0.108108, 0.      , 0.2     ,
       0.15    , 0.178571, 0.      , 0.083333, 0.102564, 0.208333,
       0.181818, 0.142857, 0.117647, 0.2     , 0.190476, 0.      ,
       0.117647, 0.129032, 0.170732, 0.142857, 0.122449, 0.137931,
       0.178571, 0.241379, 0.205882, 0.107143, 0.137931, 0.266

In [8]:
x=len(n_tt)
y=len(n_tt[0])
n_tt_sum=[]
n_tt_2=np.empty([x-1,y-1], dtype=np.float)
for i in range(1,x):
    s=0.0
    for j in range(1,y):
        if(i!=0 and j!=0):
            n_tt_2[i-1][j-1]=n_tt[i][j]
            s+=float(n_tt[i][j])
    n_tt_sum.append(s)
    #n_dt_2.append(x)
print(n_tt_2)

[[1.         0.28262829 0.08349522 ... 0.01975119 0.06815311 0.19913333]
 [0.28262829 1.         0.06314987 ... 0.02294885 0.05182183 0.2035093 ]
 [0.08349522 0.06314987 1.         ... 0.01932024 0.05582016 0.0489569 ]
 ...
 [0.01975119 0.02294885 0.01932024 ... 1.         0.02354823 0.0296562 ]
 [0.06815311 0.05182183 0.05582016 ... 0.02354823 1.         0.05182548]
 [0.19913333 0.2035093  0.0489569  ... 0.0296562  0.05182548 1.        ]]


In [9]:
x=len(n_dt)
y=len(n_dt[0])
n_dt_2=np.empty([x-1,y-1], dtype=np.float)
for i in range(1,len(n_dt)):
    x=[]
    for j in range(1,len(n_dt[i])):
        if(i!=0 and j!=0):
            n_dt_2[i-1][j-1]=n_dt[i][j]

In [10]:
n_dt_2[6]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [11]:
print(len(n_dt_2))
print(len(n_dt_2[0]))
print(len(n_dd_2))
print(len(n_tt_2))

95
223
223
95


In [12]:
n_dd_2[53][53]

1.0

In [13]:
n_dt_copy=n_dt_2.copy()

In [14]:
#SORTING MATRIX PRESERVING INDEX AND SIMILARITY SCORE
def Sort_Tuple(tup):   
    tup.sort(key = lambda x: x[1],reverse=True)  
    return tup

In [15]:
def difference(A):
    diff=[]
    for i in range(0,len(A)):
        temp=[]
        for j in range(0,len(A[i])):
             temp.append((j,float(A[i][j])))
        diff.append(temp)
    for i in range(0,len(diff)):
       Sort_Tuple(diff[i])  
    return diff

In [16]:
diff_n_dd=[]
diff_n_dd=difference(n_dd_2)
print(diff_n_dd)

[[(0, 1.0), (193, 0.4), (1, 0.352941), (16, 0.352941), (36, 0.3), (132, 0.294118), (146, 0.291667), (89, 0.266667), (85, 0.241379), (157, 0.241379), (167, 0.233333), (160, 0.230769), (199, 0.230769), (180, 0.227273), (4, 0.222222), (128, 0.21875), (129, 0.21875), (208, 0.21875), (23, 0.217391), (20, 0.210526), (111, 0.210526), (209, 0.210526), (51, 0.208333), (71, 0.208333), (198, 0.208333), (35, 0.205882), (86, 0.205882), (143, 0.205882), (7, 0.2), (34, 0.2), (59, 0.2), (62, 0.2), (65, 0.2), (75, 0.2), (101, 0.2), (136, 0.2), (214, 0.2), (215, 0.2), (90, 0.193548), (6, 0.192308), (11, 0.192308), (156, 0.192308), (9, 0.190476), (76, 0.190476), (112, 0.190476), (133, 0.190476), (161, 0.190476), (124, 0.189189), (158, 0.189189), (102, 0.185185), (201, 0.185185), (72, 0.181818), (159, 0.181818), (210, 0.181818), (67, 0.178571), (84, 0.178571), (96, 0.178571), (166, 0.176471), (32, 0.173913), (58, 0.173913), (106, 0.173913), (141, 0.173913), (204, 0.171429), (80, 0.170732), (192, 0.170732)

In [17]:
diff_n_dd[1]

[(1, 1.0),
 (4, 0.5),
 (160, 0.48),
 (16, 0.473684),
 (111, 0.473684),
 (133, 0.428571),
 (161, 0.428571),
 (210, 0.409091),
 (146, 0.384615),
 (112, 0.363636),
 (0, 0.352941),
 (204, 0.352941),
 (159, 0.347826),
 (202, 0.333333),
 (81, 0.321429),
 (199, 0.321429),
 (15, 0.32),
 (101, 0.318182),
 (166, 0.315789),
 (90, 0.3125),
 (89, 0.30303),
 (176, 0.296296),
 (129, 0.294118),
 (119, 0.285714),
 (132, 0.285714),
 (157, 0.28125),
 (58, 0.28),
 (106, 0.28),
 (165, 0.272727),
 (215, 0.27027),
 (135, 0.269231),
 (175, 0.269231),
 (84, 0.266667),
 (105, 0.263158),
 (47, 0.259259),
 (51, 0.259259),
 (53, 0.259259),
 (208, 0.257143),
 (38, 0.25),
 (50, 0.25),
 (203, 0.25),
 (154, 0.243902),
 (35, 0.243243),
 (85, 0.242424),
 (214, 0.242424),
 (33, 0.241379),
 (72, 0.24),
 (62, 0.236842),
 (167, 0.235294),
 (153, 0.234043),
 (25, 0.233333),
 (73, 0.233333),
 (118, 0.233333),
 (170, 0.233333),
 (182, 0.233333),
 (180, 0.230769),
 (114, 0.228571),
 (88, 0.225806),
 (168, 0.225806),
 (177, 0.22

In [18]:
diff_n_tt=[]
diff_n_tt=difference(n_tt_2)
print(diff_n_tt)

[[(0, 1.0), (35, 0.522575435265226), (1, 0.282628289766019), (66, 0.269011835386983), (65, 0.260391580257151), (72, 0.25576846322179), (73, 0.253498053076115), (29, 0.249561759959821), (64, 0.249445706437384), (67, 0.230807582552889), (8, 0.226616975988466), (59, 0.220932125548993), (82, 0.215611483622976), (84, 0.2132716637093), (62, 0.2111372877494), (63, 0.204745519475492), (61, 0.200516477620151), (94, 0.199133332985181), (58, 0.196207175478129), (83, 0.193785189264823), (86, 0.191534801332048), (89, 0.187373548326394), (85, 0.161457603263996), (9, 0.149087608767571), (68, 0.125588478092833), (31, 0.125184639338713), (30, 0.123286934107555), (60, 0.116809993914529), (45, 0.112276086326549), (81, 0.101588347055062), (22, 0.101213429684293), (90, 0.0978354634763544), (71, 0.0965821173029968), (24, 0.0963639089480537), (50, 0.0887684691329894), (25, 0.0884155115954717), (48, 0.0872630411569393), (49, 0.0871355771764798), (51, 0.0869484748078567), (33, 0.0865299617632129), (17, 0.08517

In [19]:
len(diff_n_dd)

223

In [20]:
# FINDING NEIGHBORS ON BASIS OF THRESHOLD VALUE
size_d=len(diff_n_dd)
#INDEX
pnei_d=[]
#SIMILARITY
pnei_d_num=[]
for i in range(0,size_d):
    nei_d=[]
    index_d=[]
    j=0
    while (float(diff_n_dd[i][j][1])>=0.5 and j<len(diff_n_dd[i])):
        nei_d.append(diff_n_dd[i][j][1])
        index_d.append(diff_n_dd[i][j][0])
        j+=1
    pnei_d.append(index_d)
    pnei_d_num.append(nei_d)

In [21]:
pnei_d

[[0],
 [1, 4],
 [2, 10, 5, 130, 91, 184, 39, 185, 190],
 [3],
 [4, 111, 133, 161, 159, 210, 160, 1],
 [5, 2, 184, 10, 130, 91],
 [6, 7, 156],
 [7, 156, 96, 6, 67, 117],
 [8, 115, 201, 70, 56, 52, 19, 220],
 [9],
 [10, 2, 5, 39, 190, 130, 91, 184],
 [11],
 [12, 187],
 [13, 156],
 [14, 70, 144, 52, 61],
 [15, 175, 73, 170, 168, 51, 58, 196],
 [16],
 [17],
 [18,
  104,
  52,
  118,
  50,
  53,
  177,
  56,
  172,
  33,
  183,
  179,
  212,
  23,
  192,
  84,
  85,
  147],
 [19, 222, 8, 153],
 [20, 75],
 [21, 169, 52, 131, 56, 172, 48, 198, 212, 147, 30, 126, 71, 127, 183, 144],
 [22, 197],
 [23, 60, 167, 53, 198, 211, 18, 50, 104, 33, 36, 201],
 [24],
 [25],
 [26],
 [27],
 [28],
 [29, 150, 148, 185],
 [30, 21, 169, 52, 56, 172],
 [31, 66, 141, 206, 187],
 [32],
 [33, 53, 50, 118, 18, 177, 104, 179, 23],
 [34, 176],
 [35, 215, 62, 63],
 [36, 23],
 [37, 134],
 [38, 47],
 [39, 190, 10, 2],
 [40, 87, 44],
 [41, 144],
 [42, 58, 135, 51, 159],
 [43],
 [44, 40, 87],
 [164, 45],
 [46],
 [47, 90, 

In [22]:
pnei_t=[]
pnei_t_num=[]
size_t=len(diff_n_tt)
for i in range(0,size_t):
    nei_t=[]
    index_t=[]
    j=0
    while (float(diff_n_tt[i][j][1])>=0.5 and j<len(diff_n_tt[i])):
        nei_t.append(diff_n_tt[i][j][1])
        index_t.append(diff_n_tt[i][j][0])
        j+=1
    pnei_t.append(index_t)
    pnei_t_num.append(nei_t)

In [23]:
len(n_dt_2[0])

223

In [24]:
#WEIGHTED AVERAGE 
w_d=[]
eta=0.7
sum_d=[]
n_dd_dnn=[]
for i in range (0,size_d):
    print(i)
    w=0.0
    s=0.0
    for j in range (0,len(pnei_d_num[i])):
        w+=(pow(eta,j)*pnei_d_num[i][j])
        s+=pnei_d_num[i][j]
    w_d.append(w)
    sum_d.append(s)
for i in range(0,size_d):
    temp=0.0
    for j in range(0,len(pnei_d[i])):
        for k in range(0,size_t): 
            temp+=(w_d[i] * float(n_dt_2[k][pnei_d[i][j]]))
    if(sum_d[i]>0):
        temp=temp/sum_d[i]
    n_dd_dnn.append(temp)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222


In [25]:
w_d

[1.0,
 1.35,
 2.543246897738,
 1.0,
 2.5819825678229997,
 2.31817199234,
 1.69481531,
 2.2504301614,
 2.3421594698638,
 1.0,
 2.4754746350889993,
 1.0,
 1.371875,
 1.3749997999999999,
 2.045456916,
 2.3659525166532003,
 1.0,
 1.0,
 2.659464087953127,
 1.8162547400000002,
 1.6533330999999998,
 2.575936404966888,
 1.6611107999999999,
 2.283631630478253,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.9199619799999998,
 2.055048316,
 2.3139803410999997,
 1.0,
 2.4638915951433904,
 1.35,
 1.9146670399999999,
 1.35,
 1.3563637,
 1.4038461,
 2.012838316,
 2.07296413,
 1.35,
 1.92254771,
 1.0,
 1.96617773,
 1.4100796,
 1.0,
 1.960106133,
 2.2439715798299997,
 1.6056063999999999,
 2.8083128601202225,
 2.4410428201584877,
 2.775625819883189,
 2.8003916515305463,
 1.392,
 1.0,
 2.6452922682471818,
 1.3705884,
 2.3790182813596,
 1.0,
 1.7546214199999999,
 2.16991520247,
 1.9494052469999998,
 1.366667,
 1.0,
 1.0,
 2.2516023855999996,
 2.1253629633399997,
 1.0,
 1.0,
 2.3154276355289998,
 2.559374798646953,
 1.0

In [26]:
n_dd_dnn

[1.0,
 4.5,
 6.463039301539409,
 1.0,
 14.387029118735583,
 5.448691593889644,
 10.181319335016,
 9.490812353460099,
 14.765645622163518,
 1.0,
 6.058039148448564,
 1.0,
 4.479591836734694,
 7.162790988426228,
 10.001791074662032,
 15.505420580967412,
 1.0,
 8.0,
 19.477096867992266,
 6.313325783947229,
 8.551724405469724,
 25.500912303473132,
 1.7085714991020569,
 12.160868399654836,
 1.0,
 1.0,
 3.0,
 2.0,
 1.0,
 3.5154223534021534,
 28.11735945481788,
 11.885054730525662,
 1.0,
 18.544863175035662,
 3.6,
 2.797078027943505,
 3.6,
 4.493975843736395,
 11.573170852349795,
 4.8511947382120715,
 2.2365032086230756,
 4.5,
 18.23821724439898,
 9.0,
 2.2532801745312967,
 4.274730191836635,
 1.0,
 11.864837992843027,
 36.15269316392079,
 7.170902046098754,
 18.80259050981765,
 15.682983069825488,
 23.172169205617557,
 18.684066070034174,
 2.6769230769230767,
 1.0,
 22.10761187741399,
 9.857691975739694,
 17.103251777375473,
 1.0,
 3.8978455702478887,
 9.630422778049908,
 2.7797578263361875,

In [27]:
w_t=[]
eta=0.7
sum_t=[]
n_tt_dnn=[]
for i in range (0,size_t):
    w=0
    s=0
    for j in range (0,len(pnei_t_num[i])):
        w+=(pow(eta,j)*pnei_t_num[i][j])
        s+=pnei_t_num[i][j]
    w_t.append(w)
    sum_t.append(s)
for i in range(0,size_t):
    temp=0.0
    for j in range(0,len(pnei_t_num[i])): 
        for k in range(0,size_d): 
            temp+=(w_t[i] * float(n_dt_2[pnei_t[i][j]][k]))
    if(sum_t[i]>0):
        temp=temp/sum_t[i]
    n_tt_dnn.append(temp)

In [28]:
w_t

[1.365802804685658,
 1.0,
 1.0,
 1.0,
 1.3911269475493002,
 1.0,
 1.3911269475493002,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.3597664491397647,
 1.3597664491397647,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.3702250288693845,
 1.0,
 1.0,
 1.0,
 1.3702250288693845,
 1.0,
 1.3804482220911547,
 1.3804482220911547,
 1.0,
 1.0,
 1.0,
 1.365802804685658,
 1.416966024274303,
 1.4878030444465562,
 1.4878030444465562,
 2.128049283598692,
 1.416966024274303,
 2.065673834233512,
 2.1156492614541302,
 2.1497731232847603,
 1.0,
 1.0,
 1.0,
 1.4337034563972524,
 1.4337034563972524,
 1.38588735526422,
 1.38588735526422,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.6428307784054423,
 1.0,
 1.0,
 1.677631595277817,
 1.6661047239522573,
 1.6810051267126405,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.3720064122464641,
 1.3562571719768404,
 1.6213864326302523,
 1.0,
 1.0,
 1.6428307784054423,
 1.0,
 1.0,
 1.0,
 1.

In [29]:
n_tt_dnn

[1.7940691450177524,
 3.0,
 5.0,
 27.0,
 25.881385386620963,
 12.0,
 25.881385386620963,
 7.0,
 1.0,
 1.0,
 1.0,
 5.0,
 6.287098073536136,
 6.287098073536136,
 2.0,
 25.0,
 24.0,
 32.0,
 29.0,
 25.0,
 15.0,
 31.0,
 35.0,
 16.0,
 19.71684914422222,
 22.0,
 13.0,
 4.0,
 19.71684914422222,
 8.0,
 1.7887275590005698,
 1.7887275590005698,
 3.0,
 1.0,
 1.0,
 1.7940691450177524,
 1.7760185993776092,
 3.5071879499950165,
 3.5071879499950165,
 4.681394129144435,
 1.7760185993776092,
 4.6967972335048636,
 4.692516806810435,
 4.662478907397055,
 26.0,
 7.0,
 7.0,
 17.704672484061227,
 17.704672484061227,
 10.72068270045085,
 10.72068270045085,
 19.0,
 6.0,
 10.0,
 8.0,
 4.0,
 5.0,
 3.0,
 4.281930245333544,
 10.0,
 1.0,
 11.787987479725414,
 11.797999918663907,
 11.773720626826986,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 4.0,
 3.0,
 3.0,
 3.0,
 4.0,
 6.0,
 1.0,
 3.0,
 1.0,
 2.687683051894989,
 1.797630436169203,
 3.178602368297104,
 2.0,
 3.0,
 4.281930245333544,
 1.0,
 

In [30]:
sum_t

[1.5225754352652259,
 1.0,
 1.0,
 1.0,
 1.5587527822132858,
 1.0,
 1.5587527822132858,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.513952070199664,
 1.513952070199664,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.5288928983848349,
 1.0,
 1.0,
 1.0,
 1.5288928983848349,
 1.0,
 1.543497460130221,
 1.543497460130221,
 1.0,
 1.0,
 1.0,
 1.5225754352652259,
 1.59566574896329,
 1.696861492066509,
 1.696861492066509,
 3.182031799555676,
 1.59566574896329,
 3.078633400753473,
 3.155991856797452,
 3.2275560194211086,
 1.0,
 1.0,
 1.0,
 1.619576366281789,
 1.619576366281789,
 1.551267650377457,
 1.551267650377457,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.9183296834363461,
 1.0,
 1.0,
 2.1347557394719443,
 2.11828878043543,
 2.141640497502196,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.5314377317806631,
 1.508938817109772,
 2.040376548890435,
 1.0,
 1.0,
 1.9183296834363461,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [31]:
sum_d

[1.0,
 1.5,
 5.902595,
 1.0,
 5.563446,
 4.254548,
 2.164022,
 4.030984,
 5.075911,
 1.0,
 5.312143,
 1.0,
 1.53125,
 1.535714,
 3.272145,
 5.188017,
 1.0,
 1.0,
 11.196537999999997,
 2.589173,
 1.933333,
 9.899323,
 1.9444439999999998,
 6.948054000000001,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.73077,
 3.6544119999999998,
 3.893933,
 1.0,
 5.845889999999999,
 1.5,
 2.738096,
 1.5,
 1.509091,
 1.5769229999999999,
 2.9044119999999998,
 2.7806319999999998,
 1.5,
 3.056981,
 1.0,
 2.617754,
 1.64932,
 1.0,
 2.8084499999999997,
 4.903473,
 2.015152,
 11.351189999999999,
 6.692913000000001,
 16.769583,
 10.341808,
 1.56,
 1.0,
 11.965527,
 1.529412,
 5.563897,
 1.0,
 2.2507580000000003,
 4.281057000000001,
 2.8051440000000003,
 1.52381,
 1.0,
 1.0,
 3.6897670000000002,
 3.800977,
 1.0,
 1.0,
 5.0459819999999995,
 8.004669000000002,
 1.0,
 4.423956,
 2.389434,
 1.933333,
 1.666667,
 1.658537,
 1.567568,
 1.529412,
 2.597132,
 5.089396000000001,
 1.88,
 1.0,
 3.0,
 3.852381,
 2.264661,
 2.746212,
 2

In [32]:
#REPLACING NON EXISTING CONNECTIONS BY WEIGHTED AVERAGE OF ROW AND COLUMN
for i in range(0,size_t):
    for j in range (0,size_d):
        avg=(n_dd_dnn[j]+n_tt_dnn[i])/2
        if(n_dt_2[i][j]<avg):
            n_dt_2[i][j]=avg

In [33]:
n_dt_2

array([[ 1.39703457,  3.14703457,  4.12855422, ...,  8.56398215,
         1.39703457,  2.6859235 ],
       [ 2.        ,  3.75      ,  4.73151965, ...,  9.16694758,
         2.        ,  3.28888892],
       [ 3.        ,  4.75      ,  5.73151965, ..., 10.16694758,
         3.        ,  4.28888892],
       ...,
       [ 1.        ,  2.75      ,  3.73151965, ...,  8.16694758,
         1.        ,  2.28888892],
       [ 1.        ,  2.75      ,  3.73151965, ...,  8.16694758,
         1.        ,  2.28888892],
       [ 1.        ,  2.75      ,  3.73151965, ...,  8.16694758,
         1.        ,  2.28888892]])

In [34]:
import numpy as np
from scipy.linalg import svd
import math

In [35]:
n_dt_2[90]

array([ 1.        ,  2.75      ,  3.73151965,  1.        ,  7.69351456,
        3.2243458 ,  5.59065967,  5.24540618,  7.88282281,  1.        ,
        3.52901957,  1.        ,  2.73979592,  4.08139549,  5.50089554,
        8.25271029,  1.        ,  4.5       , 10.23854843,  3.65666289,
        4.7758622 , 13.25045615,  1.35428575,  6.5804342 ,  1.        ,
        1.        ,  2.        ,  1.5       ,  1.        ,  2.25771118,
       14.55867973,  6.44252737,  1.        ,  9.77243159,  2.3       ,
        1.89853901,  2.3       ,  2.74698792,  6.28658543,  2.92559737,
        1.6182516 ,  2.75      ,  9.61910862,  5.        ,  1.62664009,
        2.6373651 ,  1.        ,  6.432419  , 18.57634658,  4.08545102,
        9.90129525,  8.34149153, 12.0860846 ,  9.84203304,  1.83846154,
        1.        , 11.55380594,  5.42884599,  9.05162589,  1.        ,
        2.44892279,  5.31521139,  1.88987891,  1.39687494,  2.        ,
        1.        ,  6.6022888 ,  4.97329824,  1.        ,  1.  

In [36]:
#svd
U, s, VT =  np.linalg.svd(n_dt_2[0:50,0:50])
print(U,s,VT)

[[-0.07082095 -0.18053822 -0.62191625 ...  0.0824832   0.0989681
  -0.28159018]
 [-0.07790317 -0.16562517  0.3699951  ...  0.07135444  0.14749648
   0.20003239]
 [-0.08964881 -0.14089233  0.27184597 ...  0.32625095  0.05937256
  -0.26624669]
 ...
 [-0.16426106  0.016219    0.11253851 ... -0.11249001  0.18595228
  -0.09125913]
 [-0.16426106  0.016219    0.11253851 ... -0.08352467  0.18595228
  -0.09125913]
 [-0.12324535 -0.07014796 -0.09890476 ...  0.07267408 -0.03714009
   0.09635508]] [5.74413906e+02 8.55775645e+01 1.97749160e-13 1.96859393e-13
 1.60848399e-13 1.51624048e-13 1.31665286e-13 1.29092237e-13
 1.10395437e-13 8.59950575e-14 6.92831649e-14 6.81294410e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.538

In [37]:
print(np.shape(s))
print(np.shape(U))
print(np.shape(VT))

(50,)
(50, 50)
(50, 50)


In [38]:
print(s)

[5.74413906e+02 8.55775645e+01 1.97749160e-13 1.96859393e-13
 1.60848399e-13 1.51624048e-13 1.31665286e-13 1.29092237e-13
 1.10395437e-13 8.59950575e-14 6.92831649e-14 6.81294410e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 5.53870578e-14 5.53870578e-14
 5.53870578e-14 5.53870578e-14 4.55440189e-14 3.26507325e-14
 1.69966616e-14 9.52439282e-15]


In [39]:
print(np.shape(s))
print(np.shape(U))
print(np.shape(VT))

(50,)
(50, 50)
(50, 50)


In [40]:
#converting in 2d
diagonal =np.zeros(shape=(50,50), dtype=np.float64)
for i in range(0,50):
    diagonal[i][i]=s[i]
        

In [41]:
#intialize A and B
A=np.multiply(U,diagonal)
B=np.multiply(diagonal,VT)

In [42]:
print(len(A))

50


In [43]:
len(B)

50

In [44]:
#sparsification of a similarity matrix

In [45]:
for i in range(0,size_d):
    for j in range(0,size_d):
        if j in pnei_d[i] and i in pnei_d[j]:
            n_dd_2[i][j]=n_dd_2[i][j]
        elif j not in pnei_d[i] and i not in pnei_d[j]:
            n_dd_2[i][j]=0
        else:
            n_dd_2[i][j]=0.5*n_dd_2[i][j]

In [46]:
for i in range(0,size_t):
    for j in range(0,size_t):
        if j in pnei_t[i] and i in pnei_t[j]:
            n_tt_2[i][j]=n_tt_2[i][j]
        elif j not in pnei_d[i] and i not in pnei_d[j]:
            n_tt_2[i][j]=0
        else:
            n_tt_2[i][j]=0.5*n_tt_2[i][j]

In [47]:
n_dd_2

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [48]:
#LAPLACIAN OF MATRIX for regularization
import networkx as nx
G1=nx.from_numpy_matrix(n_dd_2)
G2=nx.from_numpy_matrix(n_tt_2)

In [49]:
nx.normalized_laplacian_matrix(G1)
nx.normalized_laplacian_matrix(G2)
n_dd_3=nx.to_numpy_matrix(G1)
n_tt_3=nx.to_numpy_matrix(G2)

In [50]:
n_tt_3

matrix([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]])

In [51]:
from numpy.linalg import matrix_power

In [52]:
# taking 100 iterations for convergence 
l_d=0.5
l_t=0.5
l_l=0.5

for i in range (0,100):
    temp_1=np.multiply(n_dt_2[0:50,0:50],B) 
    temp_2=np.multiply(n_dd_3[0:50,0:50],A)            
    temp_2=l_d*temp_2
    temp_3=(np.transpose(B)).dot(B)
    x,y=np.shape(temp_3)
    temp_4=(np.identity(x,dtype=float))
    temp_4=l_l*temp_4
    temp_5=(np.transpose(n_dt_2[0:50,0:50])).dot(A)
    temp_6=n_tt_3[0:50,0:50].dot(B)
    temp_6=l_t*temp_6
    temp_7=(np.transpose(A)).dot(A)
    x1,y1=np.shape(temp_7)
    temp_8=(np.identity(x1,dtype=float))
    temp_8=l_l*temp_8
    A=(temp_1-temp_2).dot(np.linalg.pinv(temp_3+temp_4))
    B=(temp_5-temp_6).dot(np.linalg.pinv(temp_8+temp_7))
    #np.linalg.pinv(a)

In [53]:
temp_2[0]

matrix([[-2.68272346e-81,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+0

In [54]:
#result = np.zeros(shape=(len(B),len(B[0])), dtype=np.float64)
result=A.dot(B)


In [55]:
result[1]
res=result[1].copy()

In [56]:
result

matrix([[-1.53157818e-36,  3.12473827e-35, -7.55954560e-40, ...,
          7.15086969e-39, -5.09291943e-41, -7.36322489e-40],
        [-1.11135010e-35,  2.26738552e-34, -5.48538879e-39, ...,
          5.18884369e-38, -3.69554529e-40, -5.34293374e-39],
        [-1.64707143e-08,  3.36036855e-07, -8.12959586e-12, ...,
          7.69010252e-11, -5.47696633e-13, -7.91847100e-12],
        ...,
        [-1.87307434e-32,  3.82146152e-31, -9.24509835e-36, ...,
          8.74529992e-35, -6.22848825e-37, -9.00500398e-36],
        [-1.78402567e-32,  3.63978370e-31, -8.80557297e-36, ...,
          8.32953569e-35, -5.93237689e-37, -8.57689304e-36],
        [-2.24169846e-53,  4.57353144e-52, -1.10645490e-56, ...,
          1.04663894e-55, -7.45426502e-58, -1.07772036e-56]])

In [57]:
n_dt_copy[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [58]:
error=0.0
for i in range(0,50):
    for j in range(0,50):
        if(result[i].item(j)>0 and n_dt_copy[i][j]==0):
            error+=1.0
        elif(result[i].item(j)<0 and n_dt_copy[i][j]==1):
            error+=1

In [59]:
error

1117.0